# Generated by Django 3.0.1 on 2022-04-20 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgeGroup',
            fields=[
                ('age_group_id', models.AutoField(primary_key=True, serialize=False)),
                ('age_group_code', models.IntegerField()),
                ('age_group', models.CharField(max_length=20)),
                ('age_group_9', models.CharField(max_length=20)),
                ('age_group_4', models.CharField(max_length=20)),
                ('age_group_3', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('gender_id', models.AutoField(primary_key=True, serialize=False)),
                ('gender_code', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='InitialReport',
            fields=[
                ('initial_report_id', models.AutoField(primary_key=True, serialize=False)),
                ('initial_report_year_num', models.IntegerField()),
                ('initial_report_year', models.IntegerField()),
                ('initial_report_month', models.CharField(max_length=20)),
                ('initial_report_quarter', models.CharField(max_length=20)),
                ('initial_report_half_year', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_id', models.AutoField(primary_key=True, serialize=False)),
                ('region', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ReportDataMining',
            fields=[
                ('data_mining_id', models.AutoField(primary_key=True, serialize=False)),
                ('data_mining_year_num', models.IntegerField()),
                ('data_mining_year', models.IntegerField()),
                ('data_mining_quarter', models.CharField(max_length=20)),
                ('data_mining_half_year', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ReportType',
            fields=[
                ('report_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('report_type', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('source_report_id', models.IntegerField()),
                ('data_enter_date', models.DateTimeField()),
                ('first_dated_database', models.DateTimeField()),
                ('standard_strata', models.CharField(max_length=20)),
                ('num_total_drug', models.IntegerField()),
                ('num_con_drug', models.IntegerField()),
                ('num_total_pt', models.IntegerField()),
                ('data_load_quarter', models.CharField(max_length=20)),
                ('flag_dup', models.BooleanField()),
                ('report_id_for_dupgroup', models.IntegerField()),
                ('num_rpts_in_dupgroup', models.IntegerField()),
                ('fda_case_id', models.IntegerField()),
                ('age_group_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='userReport.AgeGroup')),
                ('data_mining_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='userReport.ReportDataMining')),
                ('gender_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='userReport.Gender')),
                ('initial_report_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='userReport.InitialReport')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='userReport.Region')),
                ('report_type_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='userReport.ReportType')),
            ],
        ),
    ]
